baseURL = 'https://redtalkslive.github.io/'
languageCode = 'en-us'
title = 'REDtalks.live'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke"]

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
summaryLength = 30

disqusShortname = 'redtalkslive'

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  text_color = ""
  author = ""
  favicon = ""
  body_classes = "avenir bg-near-white"
  post_content_classes = "avenir bg-near-white"
  site_logo = "/images/REDtalks.live-RedWhite.jpg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 6

[menu]
  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    url = "/articles"
    weight = 1
  [[menu.main]]
    identifier = "architecture"
    name = "Architecture"
    url = "/architecture"
    weight = 2
  [[menu.main]]
    identifier = "kb"
    name = "Knowledgebase"
    url = "/kb"
    weight = 3
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search"
    weight = 4

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/PearceNathan"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/REDtalksLive"